### ISSUE TITLE
keyboard在lol里不管用呀

### ISSUE THREAD

**Issue by hair2020** [bode135/VirtualKey_with_Ctypes#2]
大佬也有这种问题吗

**Comment by bode135** [comment]
用的人多了慢慢就被屏蔽了。
换一个方案，
或者自己用c写驱动😂



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hair2020 ***@***.***&gt;
发送时间: 2021年8月7日 23:08
收件人: bode135/VirtualKey_with_Ctypes ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[bode135/VirtualKey_with_Ctypes] keyboard在lol里不管用呀 (#2)





 
大佬也有这种问题吗
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bode135** [comment]
大漠比较好。
毕竟专门的脚本dll，实时更新。
可以用conda管理不同版本的python。
然后也可以试试我的这个virtualkey里面的其它几个方案还能用不





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hair2020 ***@***.***&gt;
发送时间: 2021年8月7日 23:08
收件人: bode135/VirtualKey_with_Ctypes ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[bode135/VirtualKey_with_Ctypes] keyboard在lol里不管用呀 (#2)





 
大佬也有这种问题吗
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
