### ISSUE TITLE
能否解释下什么叫“驱动级”？

### ISSUE THREAD

**Issue by redstoneleo** [bode135/VirtualKey_with_Ctypes#4]
我只是好奇是什么意思

**Comment by bode135** [comment]
网络游戏吃显卡, 显卡的图形学接口分为DirectX和OpenGL.  
目前主流网游都是基于DirectX 3D(D3D)实现.  
而一般的案件模拟都是系统层级的, 在windows系统上, 按下案件会产生按键消息, 加入windows的消息队列中, 排队处理.  
而D3D为了实时响应速度, 会忽略系统层的模拟, 直接监控驱动层的按键消息, 也就是直接监控玩家的键盘读写.  
你可以试试在lol用pywin32的按键模拟, lol会直接忽略掉.

**Comment by redstoneleo** [comment]
谢谢指教！

1. 用SetWindowsHookExW来hook是系统层级的吧？
2. 用Python “驱动层级监控键盘读写”可以从哪里入手？

**Comment by bode135** [comment]
一般来说找d3d游戏试一下就知道是不是驱动级了。不过即使是驱动级，也可能被游戏屏蔽了。还是得自己试。


驱动级模拟得用c和汇编写底层驱动。一般没人用python搞这个。




发自我的iPhone


------------------ 原始邮件 ------------------
发件人: redstoneleo ***@***.***&gt;
发送时间: 2021年11月3日 21:32
收件人: bode135/VirtualKey_with_Ctypes ***@***.***&gt;
抄送: bode ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[bode135/VirtualKey_with_Ctypes] 能否解释下什么叫“驱动级”？ (Issue #4)





 
谢谢指教！
  
用SetWindowsHookExW来hook是系统层级的吧？ 

用Python “驱动层级监控键盘读写”可以从哪里入手？ 
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by redstoneleo** [comment]
噢噢！主要是我不玩游戏，所以没有测试。
我搜了一下这个项目发现也没有用到SetWindowsHookExW相关函数，那你这个项目是用Python 的ctypes搞驱动层级监控吗？

**Comment by bode135** [comment]
嗯 &nbsp;等于就是用的c语言了。
我也是抄的stack上的，然后那个方法可能用的人太多被lol封了，对着mfc文档再弄了俩不成熟的新方法 😂



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: redstoneleo ***@***.***&gt;
发送时间: 2021年11月3日 21:47
收件人: bode135/VirtualKey_with_Ctypes ***@***.***&gt;
抄送: bode ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[bode135/VirtualKey_with_Ctypes] 能否解释下什么叫“驱动级”？ (Issue #4)





 
噢噢！主要是我不玩游戏，所以没有测试。
 我搜了一下这个项目发现也没有用到SetWindowsHookExW相关函数，那你这个项目是用Python 的ctypes搞驱动层级监控吗？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bode135** [comment]
浏览器的话用selenium调用浏览器驱动。
例如最近干活弄了几个自动提交周报，自动刷网课，自动订餐的脚本🤣



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: redstoneleo ***@***.***&gt;
发送时间: 2021年11月3日 21:32
收件人: bode135/VirtualKey_with_Ctypes ***@***.***&gt;
抄送: bode ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[bode135/VirtualKey_with_Ctypes] 能否解释下什么叫“驱动级”？ (Issue #4)





 
谢谢指教！
  
用SetWindowsHookExW来hook是系统层级的吧？ 

用Python “驱动层级监控键盘读写”可以从哪里入手？ 
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by redstoneleo** [comment]
谢谢！主要是我最近买了个鼠标，打开配套的软件自定义按键后退出软件，然后发现设置好的功能依然有效（并不会随着软件关闭而失效），您是否知道这是什么层级的修改呢？改的是鼠标驱动？
![image](https://user-images.githubusercontent.com/5896180/140072770-5ccaefde-4e27-4dab-be40-f220a49c5305.png)

**Comment by bode135** [comment]
😂
不太清楚你的这个鼠标，虽然我也用侧键鼠标编写过鼠标宏。
先确定是否完全退出了软件？
重启过了吗？
注意别让它开机启动，然后重启一下。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: redstoneleo ***@***.***&gt;
发送时间: 2021年11月3日 21:55
收件人: bode135/VirtualKey_with_Ctypes ***@***.***&gt;
抄送: bode ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[bode135/VirtualKey_with_Ctypes] 能否解释下什么叫“驱动级”？ (Issue #4)





 
谢谢！主要是我最近买了个鼠标，打开配套的软件自定义按键后退出软件，然后发现设置好的功能依然有效（并不会随着软件关闭而失效），您是否知道这是什么层级的修改呢？改的是鼠标驱动？
 
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bode135** [comment]
52pojie: bode-11111111Qq
csdn: 18510779120 1111111111Qq
teamviewer: ***@***.***, 11111111Qq
向日葵: 18510779120-11111111Qq--222222q
baidu: 18510779120, 1351738a
zhihu: 18510779120-11111111Qq
去哪儿: 18510779120-11111111Qq
weibo: 18510779120-11111111Qq
git： ***@***.*** #bode135 1351738a
pypi: bode135 1351738a
Actime: ***@***.***
V2ray: ***@***.***
百度网盘：18510779120-1351738a
appid: wx3c5e3402b67d714d
aliyun: bodeliang-1351738a
oa办公: LBD14062-1351738!q 
oa邮箱: ***@***.***
WX开发者: ***@***.***
hbuilderx: email-11111111Qq
ios_account_us: ***@***.*** [父母: 父母, 工作: 工作, 朋友: 朋友] -- email_pw: bhh351
微软: email-11111111Qq
docker: bode135-1351738Qq
办公电脑： root-2 [出生城市： 涟源， 相遇城市： 涟源， 第一只宠物名字： 清明]
postman: ***@***.***
网易163邮箱: ***@***.***
fiddler: ~qq.com-11111111Qq
steam: ~qq.com -gannimamama-1357924680Qq* - R13451
sms: ~qq.com-11111111Qq
openai: ~ - 11111111Qq
nodelai: ~ - 11111111Qq
scenario: ~ - 11111111Qq
depay: ~ - 11111111Qq
cloudfare: ~ - 1357924680*Qq
开悟: ~ -&nbsp;&nbsp;13579Qq24680
finalshell: bode135 - 22222222Qq
阿里云_新加坡: ～ - 1357924680*Qq
阿里云_cn: ～ - 1351738Qq@
服务器_base: ~ -&nbsp;&nbsp;13579Qq24680*小程序服务器: 123.57.234.131 - Liangbd+001
社保卡: 129385461 - 北京 (中日友好医院显示: 12938546100S)
apple: ~ - 19951021Qq
建设: ~ - 1351738QQ
